name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
      MLFLOW_USERNAME: ${{ secrets.MLFLOW_USERNAME }}
      MLFLOW_PASSWORD: ${{ secrets.MLFLOW_PASSWORD }}
      MODEL_NAME: ${{ secrets.MODEL_NAME }}
      RUN_ID: ${{ secrets.RUN_ID }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run unit tests
        run: |
          export PYTHONPATH=$(pwd)/code
          python -m pytest tests/ -v

  deploy:
    needs: test
    runs-on: ubuntu-latest
    env:
      MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
      MLFLOW_USERNAME: ${{ secrets.MLFLOW_USERNAME }}
      MLFLOW_PASSWORD: ${{ secrets.MLFLOW_PASSWORD }}
      MODEL_NAME: ${{ secrets.MODEL_NAME }}
      RUN_ID: ${{ secrets.RUN_ID }}
      DOCKER_IMAGE: samirpokharel/a3_car_price:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t $DOCKER_IMAGE .
          docker push $DOCKER_IMAGE

      - name: Deploy to AIT server via ProxyJump
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ vars.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          proxy_host: ${{ vars.PROXY_HOST }}
          proxy_username: ${{ secrets.USERNAME }}
          proxy_key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd st125989

            # 1️⃣ Create .env file dynamically with MLflow credentials
            cat <<EOF > .env
            MLFLOW_TRACKING_URI=${{ secrets.MLFLOW_TRACKING_URI }}
            MLFLOW_USERNAME=${{ secrets.MLFLOW_USERNAME }}
            MLFLOW_PASSWORD=${{ secrets.MLFLOW_PASSWORD }}
            MODEL_NAME=${{ secrets.MODEL_NAME }}
            RUN_ID=${{ secrets.RUN_ID }}
            EOF

            # 2️⃣ Stop previous containers
            docker compose down

            # 3️⃣ Start new containers (they read .env automatically)
            docker compose up -d
